services:
  app:
    build: .
    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
